# Generated by Django 4.2.16 on 2024-10-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicedescription',
            old_name='service_title',
            new_name='service',
        ),
    ]
