# Generated by Django 4.2.16 on 2024-10-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_rename_service_title_servicedescription_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='service_name',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='service_name',
            new_name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_uz',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
