# Generated by Django 4.2.16 on 2024-10-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_faq_answer_en_faq_answer_ru_faq_answer_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='certificates',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='certificates',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='certificates',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='certificates',
            name='title_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='certificates',
            name='title_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='faq_category',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='faq_category',
            name='title_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='faq_category',
            name='title_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='profession_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='profession_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='profession_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='profession_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='profession_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='profession_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='title_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='title_uz',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
